-- CityLink — website support chat: AI + operator hand-off relayed to/from Telegram.
-- Run after 0001_init.sql and 0002_telegram.sql.

-- A web conversation (anonymous visitor; id is a UUID generated by the browser).
create table if not exists public.web_chats (
  id         uuid primary key,
  mode       text default 'ai',          -- ai | operator (human took over)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Messages in a web conversation.
create table if not exists public.web_messages (
  id         uuid primary key default gen_random_uuid(),
  chat_id    uuid not null references public.web_chats(id) on delete cascade,
  role       text not null,              -- user | assistant | operator
  content    text not null,
  created_at timestamptz default now()
);

-- Maps an operator message in the support chat to the web conversation it answers.
create table if not exists public.web_relays (
  admin_msg_id bigint primary key,
  chat_id      uuid not null references public.web_chats(id) on delete cascade,
  created_at   timestamptz default now()
);

create index if not exists idx_web_messages_chat on public.web_messages(chat_id, created_at);

alter table public.web_chats    enable row level security;
alter table public.web_messages enable row level security;
alter table public.web_relays   enable row level security;
-- No policies → only the service role (Edge Functions) may touch these tables.
